### ISSUE TITLE
Triggers need to expose a reply signature

### ISSUE THREAD

**Issue by mellistibco** [TIBCOSoftware/flogo-lib#106]
Triggers need a reply signature. The expected params that a flow can map into.

**Comment by mellistibco** [comment]
triggers have:

output
and
reply

**Comment by Adirio** [comment]
By reply you mean to be able to make some data available to the trigger once the flow has ended processing the data?

For example:
CoAP triggers receives a GET request, it decides with action it should take with the handlers configuration, (maps it to the flow input trhough the mapping configuration), and then the flow replies back to the handler with the result of the flow execution, so that the trigger can answer the GET request.
